plugins { id 'com.android.application' }

android {
    namespace 'bg.simpletxtreader'
    compileSdk { version = release(37) }

    defaultConfig {
        applicationId 'bg.simpletxtreader'
        minSdk 26
        targetSdk { version = release(37) }
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
